{% set name = "cowpy" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jeffbuttars/cowpy/archive/{{ version }}.tar.gz
  sha256: f2941ddbb118309ab393e828f67b67da3dbcc9f2c4414c0b131bf9d4cb140b8f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - poetry-core >=1
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - cowpy

about:
  home: https://github.com/jeffbuttars/cowpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A cowsay clone for python in one file.

extra:
  recipe-maintainers:
    - carterbox
