{% set name = "cowpy" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jeffbuttars/cowpy/archive/{{ version }}.tar.gz
  sha256: 9f9c543538520bb0013bb0a7ba2b5567c9bb4acb19409c2b07170291a2e689ed

build:
  number: 2
  script:
  # scripts folder from upstream interferes with the entry point creation
    - rm -rf scripts
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python
  entry_points:
    - cowpy = cowpy.cow:main

requirements:
  host:
    - poetry-core >=1
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - cowpy
  commands:
    - echo "my message" | cowpy
    - cowpy --help

about:
  home: https://github.com/jeffbuttars/cowpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A cowsay clone for python in one file.

extra:
  recipe-maintainers:
    - carterbox
    - wolfv
