travis:
  secure:
    BINSTAR_TOKEN: Rz/rRj8Abv6kUhzmBmHafHGtZ9vWfOcpeFfgUA4iy+9oP4TWO3tuMcpS1YOrOqV0VGuQSiBYqzS/ZEKRuHAY0un59iJx21LuUuezhxXb0fXudfLFZcJarIY/d3f5x5AH3gIhcAbfE5eKZxdcdInBMsPLe2CKfdcPrMwl9Snps5xvDZNr3MSKznJNMyqKMFbibdIoRLKSeJkP2ForjXEM0VPCGnAZg+GPfkQSB3ZTm1sCaXG9jxaIatwyZVeFcGPoZk711TKwNlQh52U4Gc3ejzajAgupGBYyl38KP9XOfS3B68FYQc2yqZ7jcw9Six1WcrxvKEgiVfr7YT2gy9g5XbJrvOwpSdavhHGLE5CykIZlGqYgFRobHIWqknC7cjuYvLTLJqod3lwNfSwIPpjSaD13sp0Cw6g+KhvmPGtwSkXEWdjNrpVrqSRJkEepnQZICt+Vdwf7sETaIxzlY31hGiv8K9rpu7e/3SV+uEquPrkt8015hFFItlD9VVEy4aBdcnWd9R9egVC2m66rqjjfuWfAOUShXA+cl6aQ37qmSj4ufYge6b/g9t+7pvO5mfVQ70fsT8aLArG/8xpo0VNT2L+cOP5v+i3qxVuZQuoDChoT8tqtPyKDfQuwA0uv/TMvMITQHf/0HzHStKxdBcEnjFpOx7DxoO9ppaVTGJ5O4oU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
